name: Bad Workflow

on:
  workflow_dispatch:

env:
  PYTHON_VERSION: "3.10"

jobs:
  render:
    runs-on: ubuntu-latest
    steps:
      - name: Error
        run: |
          sleep 10
          exit 1
